Fixed syntax error
When doing `require("emoji-list")` I got the following error:
```
  list: require('./list');
                         ^

SyntaxError: Unexpected token ;
```

Removing the `;` fixes it.